services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: agendei
      POSTGRES_PASSWORD: agendei
      POSTGRES_DB: agendei
    volumes:
      - postgres_data:/data

volumes:
  postgres_data:
